#!/bin/bash

PER=0
RES=0
make

printf "Easy test :\n"

printf "> " ; ./disparam bonjour les cons | grep -i 3 > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi

printf "> " ; ./disparam  | grep -i 0 > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi 

printf "> " ; ./disparam  "hey    oh"| grep -i 1 > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi

printf "> " ; ./disparam  putain ca me wd| grep -i 4 > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi

printf "Difficult tests :\n"

printf "> " ; ./disparam  1 2 3 4 5 6 7 8 9 10 11 12| grep -i 12 > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi

printf "> " ; ./disparam  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 "bonjour le "| grep -i 21 > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi

printf "> " ; ./disparam  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30| grep -i 30 > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi
echo "Tests passed: $RES/7";
