#!/bin/bash

PER=0
RES=0
fichier="revstr"

make re

if [ -f $fichier ]; then
printf "Easy test :\n"

printf "> " ; ./revstr ok | grep -i ko > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi

printf "> " ; ./revstr bonjour  | grep -i ruojnob > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi 

printf "> " ; ./revstr vive Epitech| grep -i eviv > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi

printf "Difficult tests :\n"

printf "> " ; ./revstr "abcdefghijklmnopqrstuvwxyz"| grep -i zyxwvutsrqponmlkjihgfedcba > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi

printf "> " ; ./revstr "123456789"| grep -i 987654321 > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi

printf "> " ; ./revstr "bonjour a tous ca va" | grep -i "av ac suot a ruojnob" > /dev/null ;

if [ $? -eq 0 ] ;
then
    printf "OK\n"
    RES=$((RES + 1));
else
    printf "KO\n"
fi
echo "Tests passed: $RES/7";
else
	printf "The build failed, your project could not be tested.\n"
fi
